const itemRows = [
  {
    status: 1,
    description: "Sleeper sofa & loveseat",
    key: "sofa",
    measurements:"88\" W 38\"D, 66\" W 38\" D",
    condition:"Old but in good shape, cushions are still pretty firm. Haven't checked the pull-out bed, but it was rarely used. There is some cat hair!",
    images: ['loveseat1.png', 'loveseat2.jpg', 'sofabed.jpg'],
  },{
    status: 1,
    description: "Printer table",
    key: "printer",
    measurements:"",
    condition:"Fair condition. Nothing fancy, but it does the job",
    images: ['printerTable.jpg'],
  },{
    status: 1,
    description: "Buffet/console",
    key: "buffet",
    measurements:"",
    condition:"Good shape, one loose cabinet pull",
    images: ['cabinet.jpg', 'cabinet2.jpg', 'cabinet3.jpg', 'cabinet4.jpg']
  },{
    status: 1,
    description: "Vintage task chair",
    key: "task",
    measurements:"",
    condition:"Decades old (70s?), but still amazingly comfortable. (I think the cushioning must be from steel springs - still supportive and springy) The faux leather still looks pretty good.",
    images: ['deskChair.jpg', 'deskChair2.jpg'],
  },{
    status: 1,
    description: "Small bookshelf",
    key: "bkshelf",
    measurements:"24\"W x 37.5\" H",
    condition:"Handmade of solid wood. Not fancy, but sturdy. The bottom shelf is sized for LPs.",
    images: ['bookshelfSmall.jpg'],
  },{
    status: 1,
    description: "Large storage shelf",
    key: "storageshelf",
    measurements:"49\" W x 48\" H",
    condition:"Handmade of solid wood. Definitely \"rustic\" - great for storage but not for decor",
    images: ['storageShelf.jpg'],
  },{
    status: 1,
    description: "Birdfeeders",
    key: "feeders",
    measurements:"",
    condition:"Three copper-look metal birdfeeders in need of a good cleaning - take one or all",
    images: ['birdfeeders.jpg'],
  },{
    status: 1,
    description: "Shepherd's hook plant hanger",
    key: "hook",
    measurements:"8' I think? taller than a room",
    condition:"Metal ",
    images: ['plantHook.jpg'],
  },{
    status: 1,
    description: "Folding plastic table",
    key: "folding",
    measurements:"about 4' square",
    condition:"possibly Rubbermaid",
    images: ['foldingTable.jpg', 'foldingTable2.jpg'],
  },{
    status: 1,
    description: "China hutch",
    key: "hutch",
    measurements:"52\" W x 19\" D",
    condition:"Cool midcentury(?) china hutch/curio cabinet Well used but still in decent shape. (I'm 90% sure the top is removable for easier transport, can confirm)",
    images: ['chinaHutch.jpg', 'chinaHutch2.jpg'],
  },{
    status: 1,
    description: "Clothes rack",
    key: "rack",
    measurements:"",
    condition:"Metal, wheeled clothing rack",
    images: ['clothesRack.jpg'],
  },{
    status: 1,
    description: "Animal crate",
    key: "crate",
    measurements:"approx 3' W x 4' D",
    condition:"Folding wire crate with metal bottom. Got it on Freecycle - didn't end up using it, but I did wash it.",
    images: [],
  },{
    status: 1,
    description: "Vintage lounge chair",
    key: "swivel",
    measurements:"31\" W x 28\" H",
    condition:"70's faux leather swivel chair. I love this chair and wish I had room for it. It's very low (28\" high at the back). Great for a kids room, for curling up with a book, or spinning until you're dizzy.",
    images: ['swivelChair.jpg'],
  },{
    status: 1,
    description: "Three-hole punch",
    key: "3punch",
    measurements:"",
    condition:"Metal, with helper handle for leverage",
    images: ['holePunch.jpg'],
  },{
    status: 3,
    description: "Taken",
    key: "test3",
    measurements:"",
    condition:"",
    images: [],
  },{
    status: 2,
    description: "Promised",
    key: "test2",
    measurements:"",
    condition:"",
    images: [],
  },{
    status: 4,
    description: "Not posted",
    key: "test4",
    measurements:"",
    condition:"",
    images: [],
  }
];

export default itemRows;
  